version: '3.4'
services:
  explotify-backend:
    image: dockerreg.enowars.com:5000/explotify-backend
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=explotify-checker_explotify-db 
      - MONGO_PORT=27017
      - MONGO_USER=ipv6islove
      - MONGO_PASSWORD=dockerislove
    build: .
    networks:
      - bridge
      - enoverlay
    deploy:
      labels:
          - "traefik.enable=true"
          - "traefik.backend=explotify-checker_backend"
          - "traefik.docker.network=enoverlay"
          - "traefik.frontend.rule=Host:explotify.checker.enowars.com,service15.checker.enowars.com,dddd.checker.enowars.com"
          - "traefik.port=3031"
          - "traefik.backend.loadbalancer.method=drr"
      replicas: 8
      placement:
        constraints:
          - "node.hostname==enosev"

  explotify-db:
    image: mongo
    networks:
      - enoverlay
    volumes:
      - explotify_db_data:/data/db
#we need to fix the node otherwise the volumes are lost after migration :/
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==enosev"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ipv6islove
      MONGO_INITDB_ROOT_PASSWORD: dockerislove
 
        
networks:
  bridge:
    external: true
  enoverlay:
    external: true
    

volumes:
  explotify_db_data: